export const GITHUB_API_URL = "https://api.github.com";
export const GITHUB_API_TOKEN = process.env.GITHUB_API_TOKEN;
export const STACKS_ORGS = [
  "alexgo-io",
  "syvita",
  "citycoins",
  "arkadiko-dao",
  "openintents",
  "StackedSats",
  "hirosystems",
  "obylabs",
  "cryptocracy",
  "clarity-lang",
  "blockstack",
  "taraldefi",
  "Light-Labs",
  "LeastAuthority",
  "Daemon-Technologies",
  "JoinFreehold",
  "stacksgov",
  "sigle",
  "BlockSurvey",
  "hirevibes",
  "Pravica-Inc",
  "seekster",
  "bransfer",
  "weavery",
  "envelop-app",
  "TeamBandL",
  "jolocom",
];
