export const GITHUB_API_URL = "https://api.github.com";
export const GITHUB_API_TOKEN = process.env.GITHUB_API_TOKEN;
export const STACKS_TOPICS = ["stacks", "blockstack", "stx", "clarity"];
export const STACKS_ORGS = [
  "https://github.com/alexgo-io/",
  "https://github.com/syvita/",
  "https://github.com/citycoins/",
  "https://github.com/arkadiko-dao/",
  "https://github.com/openintents",
  "https://github.com/StackedSats",
  "https://github.com/hirosystems/",
  "https://github.com/obylabs/",
  "https://github.com/cryptocracy",
  "https://github.com/clarity-lang/",
  "https://github.com/blockstack",
  "https://github.com/taraldefi",
  "https://github.com/Light-Labs",
  "https://github.com/LeastAuthority",
  "https://github.com/Daemon-Technologies",
  "https://github.com/JoinFreehold",
  "https://github.com/stacksgov",
  "https://github.com/sigle",
  "https://github.com/BlockSurvey",
  "https://github.com/hirevibes",
  "https://github.com/Pravica-Inc",
  "https://github.com/seekster",
  "https://github.com/bransfer",
  "https://github.com/weavery",
  "https://github.com/envelop-app",
  "https://gitlab.com/riot.ai/",
  "https://github.com/TeamBandL",
  "https://github.com/jolocom",
];
